INSERT INTO QUENTIN_Qualification ("Développeur",  500)
INSERT INTO QUENTIN_Qualification ("Analyste",  700)
INSERT INTO QUENTIN_Qualification ("Chef de projet",  900)
INSERT INTO QUENTIN_Qualification ("Consultant", 1000)
INSERT INTO QUENTIN_Qualification ("Directeur commercial", 1300)
